apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
      - name: insureme
        image: abhishekpande285/insureme-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insureme-service
spec:
  type: NodePort
  selector:
    app: insureme
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
